# Generated by Django 5.2.8 on 2025-11-14 16:06

import bets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailNotifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[
                            ("RE", "Registration"),
                            ("SU", "Subscription"),
                            ("DI", "Disabled"),
                            ("DE", "DeletedAccount"),
                            ("BA", "Balance"),
                            ("WI", "Win"),
                            ("LO", "Lose"),
                        ],
                        max_length=3,
                    ),
                ),
                ("parameters", models.TextField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/%Y/%m/"),
                ),
                ("deadline", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("initial_odds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("current_odds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_winner", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="bets.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_events",
                to="bets.eventoption",
            ),
        ),
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("odds", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="bets.event",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to="bets.eventoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gambler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("AC", "Active"),
                            ("DI", "Disabled"),
                            ("EX", "Expired"),
                        ],
                        db_index=True,
                        default="AC",
                        max_length=3,
                    ),
                ),
                (
                    "subscription_date",
                    models.DateField(
                        blank=True,
                        default=bets.models.get_default_subscription_date,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_public", "-created_at"],
                name="bets_event_is_publ_8e3366_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["deadline", "is_public"], name="bets_event_deadlin_3244be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["creator", "-created_at"], name="bets_event_creator_a55a57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(
                fields=["user", "-created_at"], name="bets_bet_user_id_380c09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(
                fields=["event", "-created_at"], name="bets_bet_event_i_4ca827_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bet",
            index=models.Index(
                fields=["event", "user"], name="bets_bet_event_i_7a8459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gambler",
            index=models.Index(
                fields=["status", "subscription_date"],
                name="bets_gamble_status_b4534c_idx",
            ),
        ),
    ]
