# Generated by Django 5.1.7 on 2025-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_gambler_created_at_gambler_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambler',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
