# Generated by Django 5.1.7 on 2025-04-17 11:11

import bets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_gambler_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambler',
            name='subscription_date',
            field=models.DateField(blank=True, default=bets.models.get_default_subscription_date, null=True),
        ),
    ]
