# Generated by Django 5.1.7 on 2025-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_alter_gambler_subscription_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gambler',
            name='status',
            field=models.TextField(choices=[('AC', 'Active'), ('DI', 'Disabled'), ('EX', 'Expired')], default='AC', max_length=3),
        ),
    ]
